// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MsqlMcpServer.Models;

public partial class Publishers
{
    public string PubId { get; set; }

    public string PubName { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Country { get; set; }

    public virtual ICollection<Employee> Employee { get; set; } = new List<Employee>();

    public virtual PubInfo PubInfo { get; set; }

    public virtual ICollection<Titles> Titles { get; set; } = new List<Titles>();
}