// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MsqlMcpServer.Models;

public partial class Stores
{
    public string StorId { get; set; }

    public string StorName { get; set; }

    public string StorAddress { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Zip { get; set; }

    public virtual ICollection<Sales> Sales { get; set; } = new List<Sales>();
}