// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MsqlMcpServer.Models;

public partial class Titles
{
    public string TitleId { get; set; }

    public string Title { get; set; }

    public string Type { get; set; }

    public string PubId { get; set; }

    public decimal? Price { get; set; }

    public decimal? Advance { get; set; }

    public int? Royalty { get; set; }

    public int? YtdSales { get; set; }

    public string Notes { get; set; }

    public DateTime Pubdate { get; set; }

    public virtual Publishers Pub { get; set; }

    public virtual ICollection<Sales> Sales { get; set; } = new List<Sales>();

    public virtual ICollection<Titleauthor> Titleauthor { get; set; } = new List<Titleauthor>();
}